# Config file for automatic testing at travis-ci.org

language: python

env:
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=py26
  - TOXENV=pypy
  - TOXENV=lint

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install tox

# command to run tests, e.g. python setup.py test
script: tox
